[package]
name = 'LiquidswapLP'
version = '1.0.0'

[addresses]
liquidswap_lp = "0x391386dde449bfed0d34259a812e005e38a19d94cb057737e0b0af2c44a2a380"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"
